### ISSUE TITLE
[Feature Request] Entries in Multiple Categories

### ISSUE THREAD

**Issue by VinnyStalck** [wisp-forest/lavender#1]
Be able to make entries appear in multiple categories.

### Examples

- A book that has a category that lists all items added by the Caves & Cliffs update with a brush entry but also has a category that lists all entries related to Archaeology;
- Minecraft started adding the same items in different creative tabs (Doors in Building and Redstone tabs or Milk Bucket on Tools&Utilities and Food&Drinks tabs).

### Motives

- Makes it easier for players to find content if they are in multiple places;
- Avoids making entries that only links to a bunch of entries in other categories;
- In real life is very hard to categorize things by just putting them in boxes, and boxes in other boxes. Its better to have multiple labels or tags that are attached to objects.

Same as https://github.com/VazkiiMods/Patchouli/issues/95

**Comment by solonovamax** [comment]
Should probably be closed, as this has now been implemented.
